services:
  - type: web
    name: event-management
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn event_management.wsgi:application
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: .onrender.com
